FROM node:18-alpine

WORKDIR /app

# Copiar package files primero (para cache)
COPY package*.json ./
RUN npm install

# Copiar el resto del código
COPY . .

# EXPOSE 3000

# Comando correcto
CMD ["npm", "start"]